### ISSUE TITLE
Safemap data 확인

### ISSUE THREAD

**Issue by assistbig** [assistbig/bigdata#9]
Safemap data 추출 확인 바랍니다.
추출을 위한 Python Code도 함께 올렸습니다.

[[확인](https://github.com/assistbig/group02/wiki/Homework---2%EC%A3%BC%EC%B0%A8)]

**Comment by tansansu** [comment]
데이터는 샘플주신 것 같아서 올려주신 코드로 다시 받았습니다. 휴일에 쉬시지도 못하고.. 감사합니다 _ _;

**Comment by assistbig** [comment]
아닙니다. ㅎㅎ 좌표 변경도 하시고 ^^
다시 받으신 데이터로 Splunk에서 지도를 이용한 통계 결과 지표를 만들어보는 것도 좋을듯 보이네요.
본 이슈는 Close할께요.
감사합니다.
